services:

  php:
    container_name: ieducar-php
    build:
      context: docker/php
      args:
        PHP_VERSION: 8.3
        COMPOSER_VERSION: 2.7
    links:
      - postgres
      - redis
    environment:
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      DB_HOST: postgres
      PGPASSWORD: ieducar
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar

  nginx:
    container_name: ieducar-nginx
    image: nginx:1.26-alpine
    links:
      - php
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx:/etc/nginx/conf.d/
    ports:
      - ${DOCKER_NGINX_PORT:-80}:80
      - ${DOCKER_NGINX_SSL_PORT:-443}:443

  postgres:
    container_name: ieducar-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ieducar
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DOCKER_POSTGRES_PORT:-5432}:5432

  redis:
    container_name: ieducar-redis
    image: redis:7-alpine
    restart: always
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379

volumes:
    postgres:
